### PR TITLE
Use CFFI to build the Python extension

### PR DESCRIPTION
**Pull request by rouge8**
[CFFI][] is the new hotness in writing C extensions for Python, because it is supported by setuptools and works out of the box on Python 2, PyPy, and Python 3.

This module should work out of the box on Python 3, with the caveat that you need to use bytes, not strings with `regex2dfa.regex2dfa`. If you're interested in Python 3 support, you can probably encode the strings in `regex2dfa.regex2dfa` if they're not already bytes.

[CFFI]: https://cffi.readthedocs.org/en/latest/

### CODE REVIEW

**Comment by rouge8** [comment]
You'll still need to follow the MacPython [Spinning wheels](https://github.com/MacPython/wiki/wiki/Spinning-wheels) guide if you want to publish OS X wheels though.

**Comment by kpdyer** [comment]
Thanks for this. Super busy the next few days, but I'll review/test/merge this ASAP.

**Comment by rouge8** [comment]
Hmm, it looks like there was also a `regex2dfa.cRegex2dfa.Regex2dfa` type that I missed. Does anything use that?

**Comment by kpdyer** [comment]
Quick update: I was able to reproduce the issue at the heart of this problem:

```
$ [install homebrew]
$ brew install python
$ virtualenv -p /usr/local/bin/python .venv
Running virtualenv with interpreter /usr/local/bin/python
New python executable in .venv/bin/python2.7
Also creating executable in .venv/bin/python
Installing setuptools, pip, wheel...done.
$ source .venv/bin/activate
$ pip install regex2dfa
Collecting regex2dfa
  Using cached regex2dfa-0.1.7.post6-cp27-none-macosx_10_10_intel.whl
Installing collected packages: regex2dfa
Successfully installed regex2dfa-0.1.7.post6
$ python
Python 2.7.10 (default, Jul 13 2015, 12:05:58) 
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import regex2dfa
Fatal Python error: PyThreadState_Get: no current thread
Abort trap: 6
```

**Comment by kpdyer** [comment]
What's more, this also causes a segfault if I use `pip install --no-use-wheel regex2dfa` for the install.

**Comment by kpdyer** [comment]
I've tested this PR and it appears to fix the problem. As far as I can tell, no external callers do/should call `regex2dfa.cRegex2dfa.Regex2dfa`. So, this looks good. Thanks @rouge8!

**Pull request merged**
